// packages/widget/src/components/AvatarDisplay.svelte
<script lang="ts">
  import { getInitials } from '../lib/color';

  interface Props {
    avatarUrl?: string;
    username?: string;
    size?: number;
  }

  let { avatarUrl, username, size = 48 }: Props = $props();

  let initials = $derived(getInitials(username));
</script>

<div 
  class="avatar-container" 
  style:width="{size}px" 
  style:height="{size}px"
>
  {#if avatarUrl}
    <img 
      src={avatarUrl} 
      alt={username || 'Voter'} 
      class="avatar-image"
      loading="lazy"
    />
  {:else}
    <div class="avatar-fallback">
      {initials}
    </div>
  {/if}
</div>

<style>
  .avatar-container {
    border-radius: 50%;
    flex-shrink: 0;
    position: relative;
    overflow: hidden;
  }

  .avatar-image {
    width: 100%;
    height: 100%;
    border-radius: 50%;
    object-fit: cover;
    display: block;
    border: 2px solid rgba(255, 255, 255, 0.6);
    transition: opacity 0.3s ease;
  }

  .avatar-fallback {
    width: 100%;
    height: 100%;
    border-radius: 50%;
    background: rgba(0, 0, 0, 0.25);
    border: 2px solid rgba(255, 255, 255, 0.35);
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 900;
    font-size: 16px;
    color: #FFFFFF;
    font-family: system-ui, sans-serif;
  }
</style>

// packages/widget/src/components/AvatarDisplay.tsx
import React, { useState } from 'react';
import { getInitials } from '../lib/color';

interface AvatarDisplayProps {
  avatarUrl?: string | undefined;
  name?: string | undefined;
  size?: number;
  className?: string;
}

export const AvatarDisplay: React.FC<AvatarDisplayProps> = ({
  avatarUrl,
  name = '??',
  size = 48,
  className = '',
}) => {
  const [imgError, setImgError] = useState(false);

  const initials = getInitials(name);

  if (avatarUrl && !imgError) {
    return (
      <div 
        className={`avatar-wrapper ${className}`} 
        style={{ width: size, height: size, flexShrink: 0, position: 'relative' }}
      >
        <img
          src={avatarUrl}
          alt={name}
          onError={() => setImgError(true)}
          style={{
            width: size,
            height: size,
            borderRadius: '50%',
            objectFit: 'cover',
            border: '2px solid rgba(255, 255, 255, 0.65)',
            display: 'block',
          }}
        />
      </div>
    );
  }

  return (
    <div
      className={`avatar-fallback ${className}`}
      style={{
        width: size,
        height: size,
        borderRadius: '50%',
        backgroundColor: 'rgba(0, 0, 0, 0.25)',
        border: '2px solid rgba(255, 255, 255, 0.4)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 900,
        fontSize: size * 0.38,
        color: '#FFFFFF',
        flexShrink: 0,
        userSelect: 'none',
      }}
    >
      {initials}
    </div>
  );
};
