// packages/widget/src/components/DashboardOverlay.svelte
<script lang="ts">
  import { flip } from 'svelte/animate';
  import { cubicOut } from 'svelte/easing';
  import type { SessionData } from '../lib/types';
  import CandidateCard from './CandidateCard.svelte';
  import StageIndicator from './StageIndicator.svelte';

  interface Props {
    session: SessionData;
    isSessionEnded?: boolean;
    sortByRank?: boolean;
  }

  let { session, isSessionEnded = false, sortByRank = true }: Props = $props();

  let isEndingSoon = $derived(
    !isSessionEnded && session.remainingSeconds <= 10 && session.remainingSeconds > 0
  );

  let maxVotes = $derived(
    Math.max(...(session.candidates.map(c => c.votes) || [0]))
  );

  // Dynamic ranking sorted descending by votes
  let displayCandidates = $derived.by(() => {
    if (!sortByRank) return session.candidates.map((c, i) => ({ ...c, rank: i + 1 }));
    const sorted = [...session.candidates].sort((a, b) => b.votes - a.votes);
    return sorted.map((c, i) => ({ ...c, rank: i + 1 }));
  });
</script>

<div class="dashboard-root">
  <!-- Large Monospace Countdown Timer Header -->
  <div class="timer-section">
    {#if isSessionEnded || session.remainingSeconds <= 0}
      <div class="timer-finished">
        <svg class="stop-icon" viewBox="0 0 24 24">
          <path d="M6 6h12v12H6z"/>
        </svg>
        <span>VOTING SELESAI</span>
      </div>
    {:else}
      <div class="timer-display" class:ending={isEndingSoon}>
        {session.formattedTime}
      </div>
    {/if}
  </div>

  <!-- Stage Channel Banner -->
  <div class="stage-banner" class:banner-ended={isSessionEnded}>
    <span class="stage-dot" class:dot-ended={isSessionEnded}></span>
    <span>
      {#if isSessionEnded}
        🔒 Sesi voting telah berakhir · Hasil final telah dikunci
      {:else}
        🎙️ Voting hanya untuk member di Stage Channel · voice_gate_enabled: true
      {/if}
    </span>
  </div>

  <!-- Candidate Cards Grid (pet-care-dashboard style with FLIP Animation) -->
  <div class="cards-grid">
    {#each displayCandidates as candidate (candidate.id)}
      <div 
        class="card-anim-wrapper" 
        animate:flip={{ duration: 450, easing: cubicOut }}
      >
        <CandidateCard 
          {candidate}
          rank={candidate.rank}
          isWinner={isSessionEnded && candidate.votes === maxVotes && maxVotes > 0} 
        />
      </div>
    {/each}
  </div>

  <!-- Footer Stats -->
  <div class="dashboard-footer">
    Total Suara Sah: <strong>{session.totalVotes}</strong> · Mode: {session.voteMode} · 
    <span class="status-pill" class:status-ended={isSessionEnded}>
      {isSessionEnded ? '⏹ CLOSED' : '● ACTIVE'}
    </span>
  </div>
</div>

<style>
  .dashboard-root {
    width: 100%;
    max-width: 720px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 32px 20px;
    background: #FFFFFF;
    color: #0F172A;
  }

  /* Timer Section */
  .timer-section {
    margin-bottom: 6px;
    text-align: center;
  }

  .timer-display {
    font-size: 64px;
    font-weight: 900;
    font-family: var(--font-mono);
    letter-spacing: 4px;
    line-height: 1;
    color: #0F172A;
    transition: color 0.3s ease;
  }

  .timer-display.ending {
    color: var(--timer-ending);
  }

  .timer-finished {
    display: inline-flex;
    align-items: center;
    gap: 12px;
    font-size: 48px;
    font-weight: 900;
    color: var(--timer-ending);
    letter-spacing: 2px;
    line-height: 1;
  }

  .stop-icon {
    width: 44px;
    height: 44px;
    fill: var(--timer-ending);
  }

  /* Stage Banner */
  .stage-banner {
    font-size: 13px;
    font-weight: 600;
    color: var(--text-muted);
    margin-bottom: 28px;
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .stage-banner.banner-ended {
    color: #EF4444;
  }

  .stage-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background-color: #10B981;
    box-shadow: 0 0 8px #10B981;
  }

  .stage-dot.dot-ended {
    background-color: #EF4444;
    box-shadow: none;
  }

  /* Cards Grid */
  .cards-grid {
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 12px;
    position: relative;
  }

  .card-anim-wrapper {
    width: 100%;
    will-change: transform;
  }

  /* Footer */
  .dashboard-footer {
    margin-top: 28px;
    font-size: 13px;
    color: var(--text-muted);
    font-weight: 600;
  }

  .status-pill {
    color: #10B981;
    font-weight: 800;
  }

  .status-pill.status-ended {
    color: #EF4444;
  }
</style>

// packages/widget/src/components/DashboardOverlay.tsx
import React, { useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import type { SessionData } from '../lib/types';
import { CandidateCard } from './CandidateCard';

interface DashboardOverlayProps {
  session: SessionData;
  isSessionEnded?: boolean;
  sortByRank?: boolean;
}

export const DashboardOverlay: React.FC<DashboardOverlayProps> = ({
  session,
  isSessionEnded = false,
  sortByRank = true,
}) => {
  const isEndingSoon = !isSessionEnded && session.remainingSeconds <= 10 && session.remainingSeconds > 0;

  const sortedCandidates = useMemo(() => {
    if (!sortByRank) {
      return session.candidates.map((c, i) => ({ ...c, rank: i + 1 }));
    }
    const sorted = [...session.candidates].sort((a, b) => b.votes - a.votes);
    return sorted.map((c, i) => ({ ...c, rank: i + 1 }));
  }, [session.candidates, sortByRank]);

  const maxVotes = useMemo(
    () => Math.max(...session.candidates.map((c) => c.votes), 0),
    [session.candidates]
  );

  return (
    <div
      style={{
        width: '100%',
        maxWidth: '720px',
        margin: '0 auto',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '32px 20px',
        backgroundColor: '#FFFFFF',
        color: '#0F172A',
      }}
    >
      {/* 1. Large Monospace Countdown Timer */}
      <div style={{ marginBottom: '6px', textAlign: 'center' }}>
        {isSessionEnded || session.remainingSeconds <= 0 ? (
          <div
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '12px',
              fontSize: '48px',
              fontWeight: 900,
              color: '#DC2626',
              letterSpacing: '2px',
              lineHeight: 1,
            }}
          >
            <svg style={{ width: '44px', height: '44px', fill: '#DC2626' }} viewBox="0 0 24 24">
              <path d="M6 6h12v12H6z" />
            </svg>
            <span>VOTING SELESAI</span>
          </div>
        ) : (
          <div
            style={{
              fontSize: '64px',
              fontWeight: 900,
              fontFamily: 'var(--font-mono)',
              letterSpacing: '4px',
              lineHeight: 1,
              color: isEndingSoon ? '#DC2626' : '#0F172A',
              transition: 'color 0.3s ease',
              animation: isEndingSoon ? 'vote-pulse 1s infinite alternate ease-in-out' : 'none',
            }}
          >
            {session.formattedTime}
          </div>
        )}
      </div>

      {/* 2. Stage Info Banner */}
      <div
        style={{
          fontSize: '13px',
          fontWeight: 600,
          color: isSessionEnded ? '#EF4444' : '#64748B',
          marginBottom: '28px',
          display: 'flex',
          alignItems: 'center',
          gap: '6px',
        }}
      >
        <span
          style={{
            width: '8px',
            height: '8px',
            borderRadius: '50%',
            backgroundColor: isSessionEnded ? '#EF4444' : '#10B981',
            boxShadow: isSessionEnded ? 'none' : '0 0 8px #10B981',
          }}
        />
        <span>
          {isSessionEnded
            ? '🔒 Sesi voting telah berakhir · Hasil final telah dikunci'
            : '🎙️ Voting hanya untuk member di Stage Channel · voice_gate_enabled: true'}
        </span>
      </div>

      {/* 3. Candidate Cards (pet-care-dashboard style) with Framer Motion Layout Reordering */}
      <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '12px', position: 'relative' }}>
        <AnimatePresence>
          {sortedCandidates.map((candidate) => (
            <motion.div
              key={candidate.id}
              layout
              transition={{
                type: 'spring',
                stiffness: 350,
                damping: 30,
                mass: 0.8,
              }}
              style={{ width: '100%' }}
            >
              <CandidateCard
                candidate={candidate}
                rank={candidate.rank}
                isWinner={isSessionEnded && candidate.votes === maxVotes && maxVotes > 0}
              />
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {/* 4. Footer Metadata */}
      <div
        style={{
          marginTop: '28px',
          fontSize: '13px',
          color: '#64748B',
          fontWeight: 600,
          textAlign: 'center',
        }}
      >
        Total Suara Sah: <strong>{session.totalVotes}</strong> · Mode: {session.voteMode} ·{' '}
        <span style={{ color: isSessionEnded ? '#EF4444' : '#10B981', fontWeight: 800 }}>
          {isSessionEnded ? '⏹ CLOSED' : '● ACTIVE'}
        </span>
      </div>
    </div>
  );
};
