// packages/widget/src/components/StageIndicator.svelte
<script lang="ts">
  interface Props {
    isStageGated: boolean;
    stageName?: string;
    isSessionEnded?: boolean;
  }

  let { isStageGated, stageName = '#live-stage', isSessionEnded = false }: Props = $props();
</script>

{#if isStageGated}
  <div class="stage-container" class:ended={isSessionEnded}>
    <span class="stage-dot" class:dot-ended={isSessionEnded}></span>
    <span class="stage-text">
      {#if isSessionEnded}
        🔒 VOTING SELESAI · HASIL FINAL
      {:else}
        Stage Gated · {stageName}
      {/if}
    </span>
  </div>
{/if}

<style>
  .stage-container {
    text-align: center;
    font-size: 10px;
    font-weight: 800;
    color: #10B981;
    letter-spacing: 1px;
    text-transform: uppercase;
    padding-bottom: 4px;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    user-select: none;
    transition: color 0.3s ease;
  }

  .stage-container.ended {
    color: #EF4444;
  }

  .stage-dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background-color: #10B981;
    box-shadow: 0 0 8px #10B981;
    animation: pulse-dot 1.5s infinite;
  }

  .stage-dot.dot-ended {
    background-color: #EF4444;
    box-shadow: 0 0 8px #EF4444;
    animation: none;
  }

  @keyframes pulse-dot {
    0%, 100% { opacity: 1; transform: scale(1); }
    50% { opacity: 0.4; transform: scale(0.85); }
  }

  .stage-text {
    line-height: 1;
  }
</style>

// packages/widget/src/components/StageIndicator.tsx
import React from 'react';

interface StageIndicatorProps {
  isStageGated?: boolean;
  stageName?: string | undefined;
  isSessionEnded?: boolean;
}

export const StageIndicator: React.FC<StageIndicatorProps> = ({
  isStageGated = false,
  stageName = '#live-stage',
  isSessionEnded = false,
}) => {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '6px',
        fontSize: '11px',
        fontWeight: 700,
        letterSpacing: '0.4px',
        padding: '5px 12px',
        borderRadius: '20px',
        background: 'rgba(0, 0, 0, 0.45)',
        backdropFilter: 'blur(6px)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        color: isSessionEnded ? '#EF4444' : isStageGated ? '#10B981' : '#94A3B8',
        userSelect: 'none',
      }}
    >
      <span
        style={{
          width: '6px',
          height: '6px',
          borderRadius: '50%',
          backgroundColor: isSessionEnded ? '#EF4444' : isStageGated ? '#10B981' : '#94A3B8',
          boxShadow: isSessionEnded ? 'none' : isStageGated ? '0 0 8px #10B981' : 'none',
        }}
      />
      <span>
        {isSessionEnded
          ? '🔒 HASIL FINAL TERKUNCI'
          : isStageGated
          ? `Stage Gated · ${stageName}`
          : 'Voting Terbuka'}
      </span>
    </div>
  );
};
